name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Display hello world
        run: npm install