name: CI

on:
  push:
    branches:
      - armina-test
  pull_request:
    branches:
      - armina-test
  workflow_dispatch:  

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci