name: ci

on:
  push:
    branches:
      - josie
  pull_request:
    branches:
      - josie
  workflow_dispatch:
  
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Run ci
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: echo "ci"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
