name: CI

on:
  push:
    branches:
      - main
  pull requests:
    branches:
      - main


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Display hello world
        run: |
          echo "Hi rachel!"
          npm install
          npm run test
